import { writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import type { CodeAgentState } from '../state.js'

export async function summarizeNode(state: CodeAgentState): Promise<Partial<CodeAgentState>> {
  if (state.error) return {}

  const programId = state.cobolMetadata?.programId ?? state.cobolMetadata?.name ?? 'Unknown'
  const validation = state.validationResult
  const validationSection = validation
    ? `## Validation Results\n- Tests: ${validation.testCount} total, ${validation.passCount} passed, ${validation.failCount} failed\n- Status: ${validation.passed ? '✅ All tests passed' : '⚠️ Some tests failed'}\n${validation.errors.length > 0 ? `\n### Failures\n${validation.errors.map((e) => `- ${e}`).join('\n')}` : ''}`
    : '## Validation\nSkipped (--no-validate flag)'

  const rulesSection =
    state.businessRules.length > 0
      ? `## Business Rules Extracted (${state.businessRules.length})\n${state.businessRules.map((r) => `- **${r.name}** (\`${r.id}\`): ${r.description}`).join('\n')}`
      : '## Business Rules\nNone extracted'

  const filesSection =
    state.writtenPaths.length > 0
      ? `## Generated Files\n${state.writtenPaths.map((p) => `- \`${p}\``).join('\n')}`
      : '## Generated Files\nNone written'

  const externalCalls = state.cobolMetadata?.calls ?? []
  const copybooks = state.cobolMetadata?.copybooks ?? []
  const manualReview = [
    externalCalls.length > 0
      ? `External CALL targets not migrated: ${externalCalls.join(', ')}`
      : null,
    copybooks.length > 0
      ? `Copybook dependencies used: ${copybooks.join(', ')} — verify data layout equivalence`
      : null,
    state.iteration > 0
      ? `Code required ${state.iteration} fix iteration(s) — review generated code carefully`
      : null,
  ]
    .filter(Boolean)
    .map((n) => `- ${n}`)
    .join('\n')

  const notes = `# Migration Notes: ${programId}

## Source
- File: \`${state.filePath}\`
- Target language: ${state.targetLanguage}
- Lines: ${state.cobolMetadata?.lines ?? 'unknown'}

${rulesSection}

${filesSection}

${validationSection}

## Manual Review Required
${manualReview || '- No specific issues detected'}

---
*Generated by OpenCobol AI*
`

  const dest = join(resolve(state.outputDir), 'MIGRATION_NOTES.md')
  writeFileSync(dest, notes, 'utf-8')

  return {}
}
